application: markedbyme
version: 01
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /icon.png
  static_files: static/images/icon.png
  upload: static/images/icon.png

- url: /.*
  script: main.application

libraries:
  - name: django
    version: 1.4
builtins:
- django_wsgi: on