application: markedbyme
version: 01
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /.*
  script: main.application

libraries:
  - name: django
    version: 1.4
builtins:
- django_wsgi: on